### ISSUE TITLE
Conflict with other libraries

### ISSUE THREAD

**Issue by AbdallahZidano** [AhmedAbouelkher/security_tester#2]
Launching lib\main.dart on CPH1911 in debug mode...

C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\device_info_plus-8.2.2\android\src\main\kotlin\dev\fluttercommunity\plus\device_info\MethodCallHandlerImpl.kt:67:50: warning: 'getter for defaultDisplay: Display!' is deprecated. Deprecated in Java
            val display: Display = windowManager.defaultDisplay
                                                 ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\device_info_plus-8.2.2\android\src\main\kotlin\dev\fluttercommunity\plus\device_info\MethodCallHandlerImpl.kt:70:25: warning: 'getRealMetrics(DisplayMetrics!): Unit' is deprecated. Deprecated in Java
                display.getRealMetrics(metrics)
                        ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\device_info_plus-8.2.2\android\src\main\kotlin\dev\fluttercommunity\plus\device_info\MethodCallHandlerImpl.kt:72:25: warning: 'getMetrics(DisplayMetrics!): Unit' is deprecated. Deprecated in Java
                display.getMetrics(metrics)
                        ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\device_info_plus-8.2.2\android\src\main\kotlin\dev\fluttercommunity\plus\device_info\MethodCallHandlerImpl.kt:89:47: warning: 'SERIAL: String!' is deprecated. Deprecated in Java
                build["serialNumber"] = Build.SERIAL
                                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:156:38: warning: parameter 'call' is never used
    private fun checkXposedFramework(call: MethodCall, result: Result) {
                                     ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:291:36: warning: parameter 'call' is never used
    private fun checkSettingsProps(call: MethodCall, result: Result) {
                                   ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:306:31: warning: parameter 'call' is never used
    private fun checkEmulator(call: MethodCall, result: Result) {
                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:341:31: warning: parameter 'call' is never used
    private fun rootBeerCheck(call: MethodCall, result: Result) {
                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\EmulatorCheck.kt:37:26: warning: 'SERIAL: String!' is deprecated. Deprecated in Java
                || Build.SERIAL.contains("nox", ignoreCase = true)
                         ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\MagiskApp.kt:29:32: warning: 'getPackageArchiveInfo(String, Int): PackageInfo?' is deprecated. Deprecated in Java
        context.packageManager.getPackageArchiveInfo(archive.absolutePath, flags)!!
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\MagiskApp.kt:44:24: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        for (pkg in pm.queryIntentActivities(intent, PackageManager.MATCH_ALL)) {
                       ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\MagiskApp.kt:46:32: warning: 'getPackageInfo(String, Int): PackageInfo!' is deprecated. Deprecated in Java
                val pInfo = pm.getPackageInfo(pkg.activityInfo.packageName, flags)
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMConventionalAPIs.kt:16:32: warning: 'getInstalledPackages(Int): (Mutable)List<PackageInfo!>' is deprecated. Deprecated in Java
        context.packageManager.getInstalledPackages(0).forEach { list.add(it.packageName) }
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMConventionalAPIs.kt:17:32: warning: 'getInstalledApplications(Int): (Mutable)List<ApplicationInfo!>' is deprecated. Deprecated in Java
        context.packageManager.getInstalledApplications(0).forEach { list.add(it.packageName) }
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMQueryIntentActivities.kt:20:44: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        for (pkg in context.packageManager.queryIntentActivities(intent, PackageManager.MATCH_ALL))
                                           ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMSundryAPIs.kt:14:40: warning: 'getPackageUid(String, Int): Int' is deprecated. Deprecated in Java
                context.packageManager.getPackageUid(name, 0)
                                       ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XPosedFramework.kt:96:46: warning: 'getInstalledApplications(Int): (Mutable)List<ApplicationInfo!>' is deprecated. Deprecated in Java
        val applicationList = packageManager.getInstalledApplications(PackageManager.GET_META_DATA)
                                             ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:19:25: warning: 'getInstalledApplications(Int): (Mutable)List<ApplicationInfo!>' is deprecated. Deprecated in Java
        val intent = pm.getInstalledApplications(PackageManager.GET_META_DATA)
                        ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:20:20: warning: variable 'meta' initializer is redundant
        var meta = "";
                   ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:21:21: warning: variable 'meta2' initializer is redundant
        var meta2 = ""
                    ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:30:31: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
            if (pkg.metaData?.get(meta) != null || pkg.metaData?.get(meta2) != null) {
                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:30:66: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
            if (pkg.metaData?.get(meta) != null || pkg.metaData?.get(meta2) != null) {
                                                                 ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:37:17: warning: name shadowed: intent
            val intent =
                ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:38:20: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
                pm.queryIntentActivities(Intent(Intent.ACTION_MAIN), PackageManager.GET_META_DATA)
                   ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:51:37: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
                if (ainfo.metaData?.get(meta) != null || ainfo.metaData?.get(meta2) != null) {
                                    ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:51:74: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
                if (ainfo.metaData?.get(meta) != null || ainfo.metaData?.get(meta2) != null) {
                                                                         ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.2\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\FlutterToastPlugin.kt:9:48: warning: 'Registrar' is deprecated. Deprecated in Java
import io.flutter.plugin.common.PluginRegistry.Registrar
                                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.2\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:55:40: warning: 'setColorFilter(Int, PorterDuff.Mode): Unit' is deprecated. Deprecated in Java
                    gradientDrawable!!.setColorFilter(bgcolor.toInt(), PorterDuff.Mode.SRC_IN)
                                       ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.2\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:66:29: warning: 'setter for view: View?' is deprecated. Deprecated in Java
                    mToast?.view = layout
                            ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\fluttertoast-8.2.2\android\src\main\kotlin\io\github\ponnamkarthik\toast\fluttertoast\MethodCallHandlerImpl.kt:71:62: warning: 'getter for view: View?' is deprecated. Deprecated in Java
                            val textView: TextView = mToast?.view!!.findViewById(android.R.id.message)
                                                             ^
F:\Flutter Projects\itlegend_5\android\src\main\kotlin\com\jhomlala\better_player\BetterPlayer.kt:35:47: warning: 'DefaultDataSourceFactory' is deprecated. Deprecated in Java
import com.google.android.exoplayer2.upstream.DefaultDataSourceFactory
                                              ^
F:\Flutter Projects\itlegend_5\android\src\main\kotlin\com\jhomlala\better_player\BetterPlayer.kt:705:68: warning: parameter 'groupElementIndex' is never used
    private fun setAudioTrack(rendererIndex: Int, groupIndex: Int, groupElementIndex: Int) {
                                                                   ^
F:\Flutter Projects\itlegend_5\android\src\main\kotlin\com\jhomlala\better_player\BetterPlayer.kt:774:32: warning: name shadowed: context
                context?.let { context ->
                               ^
F:\Flutter Projects\itlegend_5\android\src\main\kotlin\com\jhomlala\better_player\BetterPlayerCache.kt:7:47: warning: 'ExoDatabaseProvider' is deprecated. Deprecated in Java
import com.google.android.exoplayer2.database.ExoDatabaseProvider
                                              ^
F:\Flutter Projects\itlegend_5\android\src\main\kotlin\com\jhomlala\better_player\BetterPlayerCache.kt:21:25: warning: 'ExoDatabaseProvider' is deprecated. Deprecated in Java
                        ExoDatabaseProvider(context)
                        ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.scottyab.rootbeer.BuildConfig found in modules jetified-rootbeer-0.1.0-runtime (com.github.scottyab:rootbeer:0.1.0) and jetified-rootbeer-lib-0.1.0-runtime (com.scottyab:rootbeer-lib:0.1.0)
     Duplicate class com.scottyab.rootbeer.Const found in modules jetified-rootbeer-0.1.0-runtime (com.github.scottyab:rootbeer:0.1.0) and jetified-rootbeer-lib-0.1.0-runtime (com.scottyab:rootbeer-lib:0.1.0)
     Duplicate class com.scottyab.rootbeer.RootBeer found in modules jetified-rootbeer-0.1.0-runtime (com.github.scottyab:rootbeer:0.1.0) and jetified-rootbeer-lib-0.1.0-runtime (com.scottyab:rootbeer-lib:0.1.0)
     Duplicate class com.scottyab.rootbeer.RootBeerNative found in modules jetified-rootbeer-0.1.0-runtime (com.github.scottyab:rootbeer:0.1.0) and jetified-rootbeer-lib-0.1.0-runtime (com.scottyab:rootbeer-lib:0.1.0)
     Duplicate class com.scottyab.rootbeer.util.QLog found in modules jetified-rootbeer-0.1.0-runtime (com.github.scottyab:rootbeer:0.1.0) and jetified-rootbeer-lib-0.1.0-runtime (com.scottyab:rootbeer-lib:0.1.0)
     Duplicate class com.scottyab.rootbeer.util.Utils found in modules jetified-rootbeer-0.1.0-runtime (com.github.scottyab:rootbeer:0.1.0) and jetified-rootbeer-lib-0.1.0-runtime (com.scottyab:rootbeer-lib:0.1.0)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57m 45s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_windowmanager: ^0.2.0
  hexcolor: ^3.0.1
  introduction_screen: ^3.0.2
  get: ^4.6.5
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  dio: ^5.1.2
  percent_indicator: ^4.2.2
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.5
  better_player:
    path: ../
  fluttertoast: ^8.1.1
  dio_smart_retry: ^5.0.0
  permission_handler: ^10.2.0
  path_provider:
  sizer:
  pull_to_refresh_plus: ^2.0.3
  package_info_plus:
  wakelock: ^0.6.2
  webview_flutter: ^4.0.2
  device_info_plus: ^8.0.0
  lottie: 
  path:
  root: ^2.0.4
  flutter_jailbreak_detection: ^1.10.0
  sqflite: ^2.0.3+1
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.1
  in_app_purchase: ^3.1.7
  flutter_svg: ^2.0.6
  screen_capture_event: ^1.1.1
  screen_protector: ^1.2.0
  change_app_package_name: ^1.1.0
  applist_detector_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0

**Comment by AhmedAbouelkher** [comment]
Hi,

Remove `flutter_jailbreak_detection` package or any other package using [Root beer](https://github.com/scottyab/rootbeer) library.

If you still have the same issue, consider creating an example project to reproduce the errors.

**Comment by AbdallahZidano** [comment]
I deleted all libraries that use `Root beer `and did flutter clean && flutter pub get

Launching lib\main.dart on CPH1911 in debug mode...
Parameter format not correct -
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_windowmanager-0.2.0\android\src\main\java\io\adaptant\labs\flutter_windowmanager\FlutterWindowManagerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\screen_capture_event-1.1.1\android\src\main\java\id\nizwar\screen_capture_event\ScreenCaptureEventPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:156:38: warning: parameter 'call' is never used
    private fun checkXposedFramework(call: MethodCall, result: Result) {
                                     ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:291:36: warning: parameter 'call' is never used
    private fun checkSettingsProps(call: MethodCall, result: Result) {
                                   ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:306:31: warning: parameter 'call' is never used
    private fun checkEmulator(call: MethodCall, result: Result) {
                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\ApplistDetectorFlutterPlugin.kt:341:31: warning: parameter 'call' is never used
    private fun rootBeerCheck(call: MethodCall, result: Result) {
                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\EmulatorCheck.kt:37:26: warning: 'SERIAL: String!' is deprecated. Deprecated in Java
                || Build.SERIAL.contains("nox", ignoreCase = true)
                         ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\MagiskApp.kt:29:32: warning: 'getPackageArchiveInfo(String, Int): PackageInfo?' is deprecated. Deprecated in Java
        context.packageManager.getPackageArchiveInfo(archive.absolutePath, flags)!!
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\MagiskApp.kt:44:24: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        for (pkg in pm.queryIntentActivities(intent, PackageManager.MATCH_ALL)) {
                       ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\MagiskApp.kt:46:32: warning: 'getPackageInfo(String, Int): PackageInfo!' is deprecated. Deprecated in Java
                val pInfo = pm.getPackageInfo(pkg.activityInfo.packageName, flags)
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMConventionalAPIs.kt:16:32: warning: 'getInstalledPackages(Int): (Mutable)List<PackageInfo!>' is deprecated. Deprecated in Java
        context.packageManager.getInstalledPackages(0).forEach { list.add(it.packageName) }
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMConventionalAPIs.kt:17:32: warning: 'getInstalledApplications(Int): (Mutable)List<ApplicationInfo!>' is deprecated. Deprecated in Java
        context.packageManager.getInstalledApplications(0).forEach { list.add(it.packageName) }
                               ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMQueryIntentActivities.kt:20:44: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
        for (pkg in context.packageManager.queryIntentActivities(intent, PackageManager.MATCH_ALL))
                                           ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\PMSundryAPIs.kt:14:40: warning: 'getPackageUid(String, Int): Int' is deprecated. Deprecated in Java
                context.packageManager.getPackageUid(name, 0)
                                       ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XPosedFramework.kt:96:46: warning: 'getInstalledApplications(Int): (Mutable)List<ApplicationInfo!>' is deprecated. Deprecated in Java
        val applicationList = packageManager.getInstalledApplications(PackageManager.GET_META_DATA)
                                             ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:19:25: warning: 'getInstalledApplications(Int): (Mutable)List<ApplicationInfo!>' is deprecated. Deprecated in Java
        val intent = pm.getInstalledApplications(PackageManager.GET_META_DATA)
                        ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:20:20: warning: variable 'meta' initializer is redundant
        var meta = "";
                   ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:21:21: warning: variable 'meta2' initializer is redundant
        var meta2 = ""
                    ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:30:31: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
            if (pkg.metaData?.get(meta) != null || pkg.metaData?.get(meta2) != null) {
                              ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:30:66: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
            if (pkg.metaData?.get(meta) != null || pkg.metaData?.get(meta2) != null) {
                                                                 ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:37:17: warning: name shadowed: intent
            val intent =
                ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:38:20: warning: 'queryIntentActivities(Intent, Int): (Mutable)List<ResolveInfo!>' is deprecated. Deprecated in Java
                pm.queryIntentActivities(Intent(Intent.ACTION_MAIN), PackageManager.GET_META_DATA)
                   ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:51:37: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
                if (ainfo.metaData?.get(meta) != null || ainfo.metaData?.get(meta2) != null) {
                                    ^
C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\kotlin\com\ahmed\applist_detector_flutter\library\XposedModules.kt:51:74: warning: 'get(String!): Any?' is deprecated. Deprecated in Java
                if (ainfo.metaData?.get(meta) != null || ainfo.metaData?.get(meta2) != null) {
                                                                         ^

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':applist_detector_flutter:configureNdkBuildDebug[arm64-v8a]'.
> [CXX1405] error when building with ndkBuild using C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\cpp\Android.mk: Android NDK: WARNING: Ignoring unknown import directory: F:\Flutter Projects\itlegend_5\itlegend_4\build\applist_detector_flutter\.cxx\Debug\x2r27175\prefab\arm64-v8a
  Android NDK: C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\cpp\Android.mk: Cannot find module with tag 'prefab/xposeddetector' in import path
  Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?    
  Android NDK: The following directories were searched:
  Android NDK:

  C++ build system [configure] failed while executing:
      @echo off
      "C:\\Users\\Zidano\\AppData\\Local\\Android\\Sdk\\ndk\\25.0.8775105\\ndk-build.cmd" ^
        "NDK_PROJECT_PATH=null" ^
        "APP_BUILD_SCRIPT=C:\\Users\\Zidano\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\applist_detector_flutter-0.0.1+1\\android\\src\\main\\cpp\\Android.mk" ^
        "NDK_APPLICATION_MK=C:\\Users\\Zidano\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\applist_detector_flutter-0.0.1+1\\android\\src\\main\\cpp\\Application.mk" ^
        "NDK_GRADLE_INJECTED_IMPORT_PATH=F:\\Flutter Projects\\itlegend_5\\itlegend_4\\build\\applist_detector_flutter\\.cxx\\Debug\\x2r27175\\prefab\\arm64-v8a" ^
        "APP_ABI=arm64-v8a" ^
        "NDK_ALL_ABIS=arm64-v8a" ^
        "NDK_DEBUG=1" ^
        "APP_PLATFORM=android-23" ^
        "NDK_OUT=F:\\Flutter Projects\\itlegend_5\\itlegend_4\\build\\applist_detector_flutter\\intermediates\\cxx\\Debug\\x2r27175/obj" ^
        "NDK_LIBS_OUT=F:\\Flutter Projects\\itlegend_5\\itlegend_4\\build\\applist_detector_flutter\\intermediates\\cxx\\Debug\\x2r27175/lib" ^
        -j8 ^
        "APP_SHORT_COMMANDS=false" ^
        "LOCAL_SHORT_COMMANDS=false" ^
        -B ^
        -n
    from C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android
  C:\Users\Zidano\AppData\Local\Pub\Cache\hosted\pub.dev\applist_detector_flutter-0.0.1+1\android\src\main\cpp\Android.mk:15: *** Android NDK: Aborting.    .  Stop.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_windowmanager: ^0.2.0
  hexcolor: ^3.0.1
  introduction_screen: ^3.0.2
  get: ^4.6.5
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  dio: ^5.1.2
  percent_indicator: ^4.2.2
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.5
  better_player:
    path: ../
  dio_smart_retry: ^5.0.0
  permission_handler: ^10.2.0
  path_provider:
  sizer:
  pull_to_refresh_plus: ^2.0.3
  wakelock: ^0.6.2
  webview_flutter: ^4.0.2
  lottie: 
  sqflite: ^2.0.3+1
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.2.1
  in_app_purchase: ^3.1.7
  flutter_svg: ^2.0.6
  screen_capture_event: ^1.1.1
  screen_protector: ^1.2.0
  applist_detector_flutter: ^0.0.1

**Comment by AhmedAbouelkher** [comment]
Take a look at this issue I created and pinned #1
